version: "3.5"
services:
  nats:
    # image: 'bitnami/nats:latest'
    # image: 'nats:latest'
    image: 'nats:alpine3.17'
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    networks:
      - jet
    command: --jetstream
  ripple:
    build: ./ripple
    ports:
      - 3000:3000
    depends_on:
      - nats
    networks:
      - jet
    volumes:
      - ./ripple/src:/home/app/src
      - /home/app/node_modules
  # snapshot:
  #   build: ./snapshot
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - nats
  #   networks:
  #     - jet
  #   volumes:
  #     - ./snapshot/src:/home/app/src
  #     - /home/app/node_modules

networks:
  jet:
    driver: bridge
